# Generated by Django 6.0.5 on 2026-08-16 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFamilies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_token_limit', models.PositiveIntegerField()),
                ('output_token_limit', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('GOOGLE', 'Google'), ('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('LOCAL', 'Custom')], default='GOOGLE', max_length=20)),
                ('_encrypted_api_key', models.TextField(blank=True, db_column='api_key', null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('CONNECTING', 'Connecting'), ('MAINTENANCE', 'Maintenance'), ('DEGRADED', 'Degraded')], default='OFFLINE', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='model_providers', to='iam.targetservice', to_field='client_id')),
                ('supported_families', models.ManyToManyField(blank=True, to='agents.modelfamilies')),
                ('user', models.ForeignKey(help_text='The ID of the user owning this provider.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
