# Generated by Django 6.0.5 on 2026-08-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelprovider',
            old_name='service',
            new_name='client',
        ),
    ]
