# Generated by Django 6.0.5 on 2026-08-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_service_modelprovider_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprovider',
            name='client',
        ),
    ]
